#!/bin/sh /etc/rc.common
# Copyright (C) 2017 lean <coolsnowwolf@gmail.com>

START=99

start()
{
	sysctl -w net.netfilter.nf_conntrack_max=6553500 >/dev/null
	sysctl -w net.netfilter.nf_conntrack_tcp_timeout_established=7440 >/dev/null
	sysctl -w net.netfilter.nf_conntrack_udp_timeout=60 >/dev/null
	sysctl -w net.netfilter.nf_conntrack_udp_timeout_stream=180 >/dev/null
	sysctl -w fs.nr_open=65535000 >/dev/null
	sysctl -w net.core.netdev_budget=5000 >/dev/null
	sysctl -w net.core.netdev_budget_usecs=50000 >/dev/null
	sysctl -w net.netfilter.nf_conntrack_max=629536 >/dev/null
	sysctl -w net.netfilter.nf_conntrack_buckets=65535 >/dev/null
	sysctl -w net.core.somaxconn=32768 >/dev/null
	sysctl -w net.core.netdev_max_backlog=52768 >/dev/null

	#power sche optimize
	if [ -f /sys/devices/system/cpu/intel_pstate/status ]; then
		# a=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_transition_latency)
		echo passive > /sys/devices/system/cpu/intel_pstate/status
		for file in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo "schedutil" > $file; done
	fi
	sdriver=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver 2>/dev/null)
	if [ "$sdriver" = "acpi-cpufreq" ]; then
		for file in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo "ondemand" > $file; done
		echo 5 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
		echo 60 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
	fi
	echo ladder > /sys/devices/system/cpu/cpuidle/current_governor

	a=$(ip address | grep ^[0-9] | awk -F: '{print $2}' | sed "s/ //g" | grep '^[e]' | grep -v "@" | grep -v "\.")
	b=$(echo "$a" | wc -l)
	for i in $(seq 1 $b)
	do
		c=$(echo "$a" | sed -n ${i}p)
		ethtool -K $c rx-checksum on >/dev/null 2>&1
		ethtool -K $c tx-checksum-ip-generic on >/dev/null 2>&1 || (
		ethtool -K $c tx-checksum-ipv4 on >/dev/null 2>&1
		ethtool -K $c tx-checksum-ipv6 on >/dev/null 2>&1)
		ethtool -K $c tx-scatter-gather on >/dev/null 2>&1
		ethtool -K $c gso on >/dev/null 2>&1
		ethtool -K $c tso on sg on tx on >/dev/null 2>&1
		ethtool -K $c ufo on >/dev/null 2>&1
	done

	a=$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq)
	b=$(echo -n ' : ')
	c=$(cat /proc/cpuinfo | grep 'core id' | sort -u | wc -l)
	d=$(echo -n ' Core ')
	e=$(cat /proc/cpuinfo | grep 'processor' | wc -l)
	f=$(echo -n ' Thread ')
	g=$(cat /proc/cpuinfo |grep -m1 'model name'|awk -F: '{print $2$3}')
	h=${g}' - '${a}${b}${c}${d}${e}${f}

	mkdir -p /tmp/sysinfo
	echo $h > /tmp/sysinfo/model

	# uci get network.@globals[0].packet_steering >/dev/null 2>&1
	packet_steering="$(uci get "network.@globals[0].packet_steering")"
	if [[ "$packet_steering" != "1" ]]; then
		sysctl -w net.core.rps_sock_flow_entries=0 >/dev/null
		for fileRps in $(ls /sys/class/net/e*/queues/rx-*/rps_cpus)
		do
			echo 0 > $fileRps
		done
		
		for fileRfc in $(ls /sys/class/net/e*/queues/rx-*/rps_flow_cnt)
		do
			echo 0 > $fileRfc
		done
        [ -f /etc/index.htm ] && mv /etc/index.htm /usr/lib/lua/luci/view/admin_status/index.htm
		exit 0
	fi

	rfc=4096
	cc=$(grep -c processor /proc/cpuinfo)
	rsfe=$(echo $cc*$rfc | bc)
	sysctl -w net.core.rps_sock_flow_entries=32768 >/dev/null
	cflag="0"
	cc=`expr $cc - 1`
	for z in `seq $cc`
	do
		cflag="1${cflag}"
	done
	cc=`echo "ibase=2;obase=10000;$cflag"|bc`

	
	for fileRps in $(ls /sys/class/net/e*/queues/rx-*/rps_cpus)
	do
		eth_name=$(echo "$fileRps"|awk -F/ '{print $5}')
		queues_count=$(find /sys/class/net/$eth_name/queues/ -name 'rx-*'|wc -l)
		if [ $queues_count = 1 ]; then
		echo $cc > $fileRps
		fi
	done
	
	for fileRfc in $(ls /sys/class/net/e*/queues/rx-*/rps_flow_cnt)
	do
		eth_name=$(echo "$fileRfc"|awk -F/ '{print $5}')
		queues_count=$(find /sys/class/net/$eth_name/queues/ -name 'rx-*'|wc -l)
		if [ $queues_count = 1 ]; then
		echo $rfc > $fileRfc
		fi
	done

	[ -f /etc/index.htm ] && mv /etc/index.htm /usr/lib/lua/luci/view/admin_status/index.htm
}
