#!/bin/sh /etc/rc.common
# Copyright (C) 2017 lean <coolsnowwolf@gmail.com>

START=99

start()
{
	sysctl -w net.netfilter.nf_conntrack_max=6553500 >/dev/null
	sysctl -w net.netfilter.nf_conntrack_tcp_timeout_established=432000 >/dev/null
	sysctl -w net.netfilter.nf_conntrack_udp_timeout=120 >/dev/null
	sysctl -w net.netfilter.nf_conntrack_udp_timeout_stream=180 >/dev/null
	sysctl -w fs.nr_open=65535000 >/dev/null
	sysctl -w net.core.netdev_budget=5000 >/dev/null
	sysctl -w net.core.netdev_budget_usecs=50000 >/dev/null
	sysctl -w net.netfilter.nf_conntrack_max=629536 >/dev/null
	sysctl -w net.netfilter.nf_conntrack_buckets=65535 >/dev/null
	sysctl -w net.core.somaxconn=32768 >/dev/null
	sysctl -w net.core.netdev_max_backlog=52768 >/dev/null
	sysctl -w net.ipv4.tcp_max_syn_backlog=65536 >/dev/null
	sysctl -w net.ipv4.tcp_rmem="65536 524288 8388608" >/dev/null
	sysctl -w net.ipv4.tcp_wmem="65536 524288 8388608" >/dev/null
	sysctl -w net.ipv4.tcp_adv_win_scale="-2" >/dev/null
	sysctl -w net.ipv4.tcp_collapse_max_bytes=6291456 >/dev/null
	sysctl -w net.ipv4.tcp_notsent_lowat=131072 >/dev/null

	if [ -f /sys/devices/system/cpu/intel_pstate/status ]; then
		echo passive > /sys/devices/system/cpu/intel_pstate/status
		for file in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo "schedutil" > $file; done
	else
		#power sche optimize
		if [[ ! -f /etc/init.d/cpufreq || ! -f /etc/config/cpufreq ]]; then
			if [ -f /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver ]; then
				for file in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo "ondemand" > $file; done
				echo 10 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
				echo 70 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
				echo 1 > /sys/devices/system/cpu/cpufreq/ondemand/ignore_nice_load
			fi
		fi
	fi
	echo ladder > /sys/devices/system/cpu/cpuidle/current_governor

	a=$(ip address | grep ^[0-9] | awk -F: '{print $2}' | sed "s/ //g" | grep '^[e]' | grep -v "@" | grep -v "\.")
	b=$(echo "$a" | wc -l)
	for i in $(seq 1 $b)
	do
		c=$(echo "$a" | sed -n ${i}p)
		ethtool -K $c rx-checksum on >/dev/null 2>&1
		ethtool -K $c tx-checksum-ip-generic on >/dev/null 2>&1 || (
		ethtool -K $c tx-checksum-ipv4 on >/dev/null 2>&1
		ethtool -K $c tx-checksum-ipv6 on >/dev/null 2>&1)
		ethtool -K $c tx-scatter-gather on >/dev/null 2>&1
		ethtool -K $c gso on >/dev/null 2>&1
		ethtool -K $c tso on sg on tx on >/dev/null 2>&1
		ethtool -K $c ufo on >/dev/null 2>&1
	done

	a=$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq)
	b=$(echo -n ' : ')
	c=$(cat /proc/cpuinfo | grep 'core id' | sort -u | wc -l)
	d=$(echo -n 'C')
	e=$(cat /proc/cpuinfo | grep 'processor' | wc -l)
	f=$(echo -n 'T ')
	g=$(dmesg | grep 'DMI:' | awk -F ',' '{print $1 }' | awk -F ':' '{print $2 }')
	if [ -d /sys/devices/cpu_atom/ ]; then
    pcore=$(cat /sys/devices/cpu_core/cpus | awk -F- '{print $2}') 
    pc=$(echo "($pcore+1)/2" | bc) 
    ecore1=$(cat /sys/devices/cpu_atom/cpus | awk -F- '{print $1}') 
    ecore2=$(cat /sys/devices/cpu_atom/cpus | awk -F- '{print $2}')
    ec=$(echo "$ecore2-$ecore1+1" | bc) 
    hydrid='('${pc}'P+'${ec}'E)'
  fi
	
	h=${g}' - '${a}${b}${c}${d}${e}${f}${hydrid}

	mkdir -p /tmp/sysinfo
	echo $h > /tmp/sysinfo/model
	
	all_pcis=`lspci | grep -i 'eth' | grep -i 'x550' | cut -d ' ' -f 1`
	all_ifs=`cat /proc/net/dev | grep -i 'eth' | cut -d :  -f 1 | sed 's/^[ \t]*//g'`

	for ifname in ${all_ifs}
	do
		if_pci=`ethtool -i ${ifname} | grep -i 'bus-info' | cut -d : -f 3-`
		if [[ "$all_pcis" =~ "$if_pci" ]]
		then
			ethtool -s ${ifname} advertise 0x1800000001028
		fi
	done

	# uci get network.@globals[0].packet_steering >/dev/null 2>&1
	packet_steering="$(uci get "network.@globals[0].packet_steering")"
	if [[ "$packet_steering" != "1" ]]; then
		sysctl -w net.core.rps_sock_flow_entries=0 >/dev/null
		for fileRps in $(ls /sys/class/net/e*/queues/rx-*/rps_cpus)
		do
			echo 0 > $fileRps
		done
		
		for fileRfc in $(ls /sys/class/net/e*/queues/rx-*/rps_flow_cnt)
		do
			echo 0 > $fileRfc
		done
        [ -f /etc/index.htm ] && mv /etc/index.htm /usr/lib/lua/luci/view/admin_status/index.htm
		exit 0
	fi

	rfc=4096
	cc=$(grep -c processor /proc/cpuinfo)
	rsfe=$(echo $cc*$rfc | bc)
	sysctl -w net.core.rps_sock_flow_entries=32768 >/dev/null
	cflag="0"
	cc=`expr $cc - 1`
	for z in `seq $cc`
	do
		cflag="1${cflag}"
	done
	cc=`echo "ibase=2;obase=10000;$cflag"|bc`

	
	for fileRps in $(ls /sys/class/net/e*/queues/rx-*/rps_cpus)
	do
		eth_name=$(echo "$fileRps"|awk -F/ '{print $5}')
		queues_count=$(find /sys/class/net/$eth_name/queues/ -name 'rx-*'|wc -l)
		if [ $queues_count = 1 ]; then
		echo $cc > $fileRps
		fi
	done
	
	for fileRfc in $(ls /sys/class/net/e*/queues/rx-*/rps_flow_cnt)
	do
		eth_name=$(echo "$fileRfc"|awk -F/ '{print $5}')
		queues_count=$(find /sys/class/net/$eth_name/queues/ -name 'rx-*'|wc -l)
		if [ $queues_count = 1 ]; then
		echo $rfc > $fileRfc
		fi
	done

	[ -f /etc/index.htm ] && mv /etc/index.htm /usr/lib/lua/luci/view/admin_status/index.htm
}