#!/bin/sh

MHz=`grep 'MHz' /proc/cpuinfo | cut -c11- |sed -n '1p'`

if [ -d /sys/devices/system/cpu/cpufreq/policy0 ]; then
if [ "$(grep 'AMD' /proc/cpuinfo)" != "" ]; then
TEMP=`sensors 2>/dev/null | grep 'Tctl' | cut -c16-`
else
TEMP=`sensors 2>/dev/null | grep 'Core 0' | cut -c12-`
fi
fi

echo "$MHz MHz $TEMP "
